### PR TITLE
Remove the multiplayer restriction from getting monster codex entries

### PR DESCRIPTION
**Pull request by DrPyspy**

### CODE REVIEW

**Comment by DrPyspy** [comment]
I may have accidentally just included a separate commit that removes the co-op restriction from marauders oops

**Comment by DrPyspy** [comment]
I can confirm marauders work just fine in co-op however, whether or not you wish to include it is up to your discretion and spiritual beliefs

**Comment by TheKins** [comment]
IIRC I disabled Codex stuff in co-op because it was causing desynchs. Have you noticed or taken care of any of those?

**Comment by DrPyspy** [comment]
looks like I wrote the codex entry giving code to use consoleplayer... even though I have the target to check for right there 🤔

I shall rectify this bit and update the branch soon

**Comment by DrPyspy** [comment]
begone pull request.... you shall turn with a new form.....

**Pull request closed without merging**
